clearances/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r"^clearances/ucr/", include('ucr.urls')),
    url(r"^admin/", admin.site.urls)
]

ucr/urls.py
"""ucr urls config"""

from django.conf.urls import url

from . import views

app_name = 'ucr'
urlpatterns = [
    url(r'^$', views.county, name='base'),
    url(r'^county/(?P<selected_county>[A-Z\s]+)$', views.department, name='department_select'),
    url(r'^(?P<ori>WA[A-Z0-9]{2}[0-9]{3})/(?P<year>[0-9]{4})/$', views.single_year, name='single_year'),
    url(r'^(?P<ori>WA[A-Z0-9]{2}[0-9]{3})/(?P<crime>[a-z_]+)/$', views.multi_year, name='multi_year'),
    url(r'^(?P<ori>WA[A-Z0-9]{2}[0-9]{3})/$', views.multi_year, name='multi_year'),
    url(r'^(?P<ori>WASPD00)/(?P<year>[0-9]{4})/$', views.single_year, name='single_year'),
    url(r'^(?P<ori>WASPD00)/(?P<crime>[a-z_]+)/$', views.multi_year, name='multi_year'),
    url(r'^(?P<ori>WA[A-Z0-9]{2}[0-9]{3})/rates/(?P<crime>[a-z_]+)/$', views.multi_year_rates, name='multi_year_rates')
]

ucr/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.utils.encoding import python_2_unicode_compatible


@python_2_unicode_compatible
class Agency(models.Model):
    ori = models.CharField(max_length=7, primary_key=True)
    department = models.CharField(max_length=50)
    county = models.CharField(max_length=50, blank=True)
    lat = models.DecimalField(max_digits=9, decimal_places=6, null=True)
    lon = models.DecimalField(max_digits=9, decimal_places=6, null=True)

    def __str__(self):
        return '%s' % (self.department)


@python_2_unicode_compatible
class IncidentsClearances(models.Model):
    ori = models.ForeignKey("Agency", on_delete=models.CASCADE)
    year = models.PositiveSmallIntegerField()
    homicide = models.PositiveSmallIntegerField()
    rape = models.PositiveSmallIntegerField()
    robbery = models.PositiveSmallIntegerField()
    aggravated_assault = models.PositiveSmallIntegerField()
    burglary = models.PositiveSmallIntegerField()
    larceny = models.PositiveSmallIntegerField()
    gta = models.PositiveSmallIntegerField()
    violent = models.PositiveSmallIntegerField()
    property = models.PositiveIntegerField()
    clearance_homicide = models.PositiveIntegerField()
    clearance_rape = models.PositiveSmallIntegerField()
    clearance_robbery = models.PositiveSmallIntegerField()
    clearance_aggravated_assault = models.PositiveSmallIntegerField()
    clearance_burglary = models.PositiveSmallIntegerField()
    clearance_larceny = models.PositiveSmallIntegerField()
    clearance_gta = models.PositiveSmallIntegerField()
    clearance_violent = models.PositiveSmallIntegerField()
    clearance_property = models.PositiveSmallIntegerField()
    population = models.PositiveIntegerField()
    pop_group = models.PositiveIntegerField()

    def __str__(self):
        return '%s %s' % (self.ori.department, self.year)


@python_2_unicode_compatible
class GroupRates(models.Model):
    pop_group = models.PositiveIntegerField()
    year = models.PositiveSmallIntegerField()
    cl_violent = models.DecimalField(max_digits=5, decimal_places=2, default=0)
    cl_property = models.DecimalField(max_digits=5, decimal_places=2, default=0)
    cl_homicide = models.DecimalField(max_digits=5,decimal_places=2, default=0)
    cl_rape = models.DecimalField(max_digits=5,decimal_places=2, default=0)
    cl_robbery = models.DecimalField(max_digits=5,decimal_places=2, default=0)
    cl_aggravated_assault = models.DecimalField(max_digits=5,decimal_places=2, default=0)
    cl_burglary = models.DecimalField(max_digits=5,decimal_places=2, default=0)
    cl_larceny = models.DecimalField(max_digits=5,decimal_places=2, default=0)
    cl_gta = models.DecimalField(max_digits=5,decimal_places=2, default=0)
    r_violent = models.DecimalField(max_digits=6,decimal_places=1,default=0)
    r_property = models.DecimalField(max_digits=6,decimal_places=1,default=0)
    r_homicide = models.DecimalField(max_digits=6,decimal_places=1,default=0)
    r_rape = models.DecimalField(max_digits=6,decimal_places=1,default=0)
    r_robbery = models.DecimalField(max_digits=6,decimal_places=1,default=0)
    r_aggravated_assault = models.DecimalField(max_digits=6,decimal_places=1,default=0)
    r_burglary = models.DecimalField(max_digits=6,decimal_places=1,default=0)
    r_larceny = models.DecimalField(max_digits=6,decimal_places=1,default=0)
    r_gta = models.DecimalField(max_digits=6,decimal_places=1,default=0)


    def __str__(self):
        return '%s %s' % (self.pop_group, self.year)

ucr/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from decimal import *
#from django.http import HttpResponse
from django.shortcuts import render
from django.db.models import Sum
from .models import *


def county(request):
    counties_tuple = list(Agency.objects.order_by('county').values_list('county').distinct())
    counties = [county_name[0] for county_name in counties_tuple]
    context = {'counties': counties}
    return render(request, 'county_select.html', context)


def department(request, selected_county):
    leas = Agency.objects.filter(county=selected_county)
    lea_details = [[agency.department, agency.ori] for agency in leas]
    context = {'departments': lea_details, 'county': selected_county}
    return render(request, 'department_select.html', context)


def single_year(request, year, ori):
    agency = Agency.objects.get(ori=ori)
    lea = agency.department.replace('_', ' ').upper()
    try:
        agency_stats = IncidentsClearances.objects.filter(ori=agency.ori).get(year=year)
    except:
        return render(request, 'nodata.html')
    group_stats = GroupRates.objects.filter(pop_group=agency_stats.population).get(year=year)
    index_crimes = ['homicide', 'rape', 'robbery', 'aggravated_assault', 'burglary', 'larceny', 'gta']
    incidents = []
    #index_counter = 0
    for crime in index_crimes:
        #crime in index_crimes:
        no_incidents = getattr(agency_stats, crime)
        try:
            r_incidents = (Decimal(no_incidents)/Decimal(agency_stats.pop_group)) * 100000
            r_incidents = r_incidents.quantize(Decimal('10.01'))
        except DivisionByZero or InvalidOperation:
            r_incidents = False
        no_clearances = getattr(agency_stats, "clearance_" + crime)
        try:
            clearance_rate = Decimal(no_clearances)/Decimal(no_incidents) * 100
            clearance_rate = clearance_rate.quantize(Decimal('10.01'))
        except InvalidOperation:
            clearance_rate = False
        r_group = getattr(group_stats, "r_" + crime)
        group_clearance_rate = getattr(group_stats, "cl_" + crime)
        group_cleared_ratio = r_group * group_clearance_rate
        group_uncleared_ratio = r_group - group_cleared_ratio
        cleared_ratio = False
        uncleared_ratio = False
        if r_incidents and clearance_rate:
                cleared_ratio = r_incidents * clearance_rate/100
                uncleared_ratio = r_incidents * (Decimal(100) - clearance_rate)/Decimal(100)
        if crime == "gta":
            crime = 'vehicle theft'
        if crime == "aggravated_assault":
            crime = 'aggravated assault'
        incidents.append(
            [no_incidents,
             r_incidents,
             r_group,
             no_clearances,
             clearance_rate,
             group_clearance_rate,
             crime,
             [r_group * Decimal(0.5), r_group * Decimal(1.5), r_group * Decimal(2)],
             [group_clearance_rate * Decimal(0.4), group_clearance_rate * Decimal(0.7), group_clearance_rate * Decimal(2)],
             cleared_ratio,
             uncleared_ratio,
             group_cleared_ratio,
             group_uncleared_ratio
             ])
    context = {"jurisdiction": lea, "county": agency.county, "year": year, "incidents": incidents}
    return render(request, 'single_year.html', context)


def multiple_year(request, startyear=2005, endyear=2015, lea=None, ori=None):
    years = range(int(startyear), int(endyear) + 1)
    if lea:
        lea_cleaned = lea.replace('_', ' ').upper()
        agency = Agency.objects.get(department=lea_cleaned)
    else:
        agency = Agency.objects.get(ori=ori)
        lea_cleaned = agency.department.replace('_', ' ').upper()
    try:
        agency_stats = IncidentsClearances.objects.filter(ori=agency.ori).filter(year__in=years)
    except:
        return render(request, 'nodata.html')
    years_reported = []
    for ucr in agency_stats:
        violent_crime = ucr.homicide + ucr.rape + ucr.robbery + ucr.aggravated_assault
        violent_crime_rate = (Decimal(violent_crime) / Decimal(ucr.pop_group)) * 100000
        violent_crime_rate = violent_crime_rate.quantize(Decimal('10.1'))
        violent_clearances = ucr.clearance_homicide + ucr.clearance_rape + ucr.clearance_robbery + ucr.clearance_aggravated_assault
        violent_clearance_rate = Decimal(violent_clearances)/Decimal(violent_crime) * 100
        violent_clearance_rate = violent_clearance_rate.quantize(Decimal('10.01'))
        property_crime = ucr.burglary + ucr.larceny + ucr.gta
        property_clearances = ucr.clearance_burglary + ucr.clearance_larceny + ucr.clearance_gta
        property_crime_rate = (Decimal(property_crime)/Decimal(ucr.pop_group)) * 100000
        property_crime_rate = property_crime_rate.quantize(Decimal('10.1'))
        property_clearance_rate = Decimal(property_clearances)/Decimal(property_crime) *100
        property_clearance_rate = property_clearance_rate.quantize(Decimal('10.01'))
        group_stats = GroupRates.objects.filter(year=ucr.year).get(pop_group=ucr.population)
        agency_stats = [ucr.year, {'avt': violent_crime, 'av': violent_crime_rate, 'avc': violent_clearance_rate, 'apt': property_crime, 'ap': property_crime_rate, 'apc': property_clearance_rate, 'gv':group_stats.r_violent, 'gvc':group_stats.cl_violent, 'gp':group_stats.r_property, 'gpc':group_stats.cl_property}]
        years_reported.append(agency_stats)
    context = {"jurisdiction":lea_cleaned, 'crime_stats':years_reported, 'year_list':years}
    return render(request, 'multi_year.html', context)


def multi_year(request, startyear=2005, endyear=2015, lea=None, ori=None, crime="violent"):
    years = range(int(startyear), int(endyear) + 1)
    agency = Agency.objects.get(ori=ori)
    lea_cleaned = agency.department
    agency_stats = IncidentsClearances.objects.filter(ori=agency.ori).filter(year__in=years)
    years_reported = []
    no_data = [0, 0]
    for ucr in agency_stats:
        year = ucr.year
        incidents = getattr(ucr, crime)
        clearances = getattr(ucr, "clearance_" + crime)
        try:
            crime_rate = (Decimal(incidents)/Decimal(ucr.pop_group)) * 100000
            crime_rate = crime_rate.quantize(Decimal('10.1'))
        except (InvalidOperation, DivisionByZero):
            crime_rate = None
            no_data[0] += 1
        try:
            clearance_rate = Decimal(clearances)/Decimal(incidents)
            clearance_rate = clearance_rate.quantize(Decimal('.0001'))
        except InvalidOperation:
            clearance_rate = None
            no_data[1] += 1
        except DivisionByZero:
            clearance_rate = 1
        group_stats = GroupRates.objects.filter(year=year).get(pop_group=ucr.population)
        group_rate = getattr(group_stats, "r_" + crime)
        group_clearance_rate = getattr(group_stats, "cl_" + crime)
        chart_data = dict(year=year, clearance_rate=clearance_rate, group_clearance_rate=group_clearance_rate / 100,
                          crime_rate=crime_rate, group_rate=group_rate, incidents=incidents, clearances=clearances)
        years_reported.append(chart_data)
    """if crime in ("violent", "property"):
        crime += " crime"
    elif crime == "gta":
        crime = "vehicle theft"""
    rate_chart = True
    clearance_chart = True
    if no_data[0] >= len(years_reported):
        rate_chart = False
    if no_data[1] >= len(years_reported):
        clearance_chart = False
    context = dict(county=agency.county, rate_chart=rate_chart, clearance_chart=clearance_chart,
                   jurisdiction=lea_cleaned, crime=crime, crime_stats=years_reported,
                   years=str(years[0]) + "-" + str(years[-1]))
    return render(request, 'chart.html', context)


def multi_year_rates(request, startyear=2005, endyear=2015, ori=None, crime="violent"):
    years = range(int(startyear), int(endyear) + 1)
    agency = Agency.objects.get(ori=ori)
    lea_cleaned = agency.department
    agency_stats = IncidentsClearances.objects.filter(ori=agency.ori).filter(year__in=years)
    years_reported = []
    no_data = 0
    for ucr in agency_stats:
        year = ucr.year
        incidents = getattr(ucr, crime)
        try:
            crime_rate = (Decimal(incidents)/Decimal(ucr.pop_group)) * 100000
            crime_rate = crime_rate.quantize(Decimal('10.1'))
        except (InvalidOperation, DivisionByZero):
            crime_rate = None
            no_data += 1
        group_stats = GroupRates.objects.filter(year=year).get(pop_group=ucr.population)
        group_rate = getattr(group_stats, "r_" + crime)
        chart_data = {'year': year, 'crime_rate': crime_rate, 'group_rate': group_rate, 'incidents': incidents}
        years_reported.append(chart_data)
    if crime in ("violent", "property"):
        crime += " crime"
    elif crime == "gta":
        crime = "vehicle theft"
    if no_data >= len(years_reported):
        rate_chart = False
    else:
        rate_chart = True
    context = dict(county=agency.county, rate_chart=rate_chart, jurisdiction=lea_cleaned, crime=crime,
                   crime_stats=years_reported, years=str(years[0]) + "-" + str(years[-1]))
    return render(request, 'rates.html', context)


def crimes_and_clearances(request, county, lea=None, startyear='2005', endyear='2015'):
    if startyear == endyear:
        years = [int(startyear)]
    else:
        years = range(int(startyear), int(endyear) + 1)
    county_cleaned = county.replace('_', ' ').upper()
    if not lea:
        agencies = Agency.objects.filter(county=county_cleaned)
        jurisdiction = county_cleaned + " COUNTY"
    else:
        lea_cleaned = lea.replace('_', ' ').upper()
        agencies = Agency.objects.filter(department=lea_cleaned)
        jurisdiction = lea_cleaned
    cc = IncidentsClearances.objects.filter(ori__in=agencies).filter(year__in=years)

templates/ucr/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ jursidiction }} Crimes and Clearances</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.css" />
    <style>

    </style>

</head>
<body>
<div class="container">
    <ol class="breadcrumb">
        <li>
            <a href="{% url 'ucr:base' %}">HOME</a>
        </li>
        <li>
            <a href="{% url 'ucr:department_select' county %}">{{ county }} COUNTY</a>
        </li>
            <li class="active">{{ jurisdiction }}</li>

    </ol>



</div><!--end bootstrap container-->
</body>
</html>

templates/ucr/templates/chart.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ jursidiction }} Crimes and Clearances</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.css" />
    <style>
        .ucr-tooltip {
            padding: 10px;
        }

        .ucr-details span {
            font-size: 1.4em;
        }

    </style>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
        <script src="https://code.jquery.com/jquery-3.2.1.min.js"
                  integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
                  crossorigin="anonymous"></script>
	<script type="text/javascript" src="https://pym.nprapps.org/pym.v1.min.js"></script>
        <script type="text/javascript">

           let crimeType = "{{ crime }}";
            crimeType = crimeType.replace("_", " ");
            if (crimeType in ["violent", "property"]){
                crimeType += " crimes"
            }
            if (crimeType == 'gta'){
                crimeType = 'vehicle theft'
            }

            const plural = {
                "violent": "violent crimes",
                "property": "property crimes",
                "homicide": "homicides",
                "rape": "rapes",
                "robbery": "robberies",
                "aggravated assault": "aggravated assaults",
                "burglary": "burglaries",
                "larceny": "larcenies",
                "vehicle theft": "vehicle thefts"
            };

          //noinspection JSUnresolvedVariable
            google.charts.load('current', {'packages':['corechart']});

          {% if clearance_chart %}
              google.charts.setOnLoadCallback(clearanceChart);

          function clearanceChart() {
              var data = new google.visualization.DataTable();
                    data.addColumn('string', 'YEAR');
                    data.addColumn('number', "{{ jurisdiction | safe }} CLEARANCE RATE");
                    data.addColumn({'type': 'string', 'role': 'tooltip', 'p': {'html': true}});
                    data.addColumn('number', 'U.S. AVERAGE CLEARANCE RATE');
                    data.addRows([
                            {% for year in crime_stats %}
                                {% if year.clearance_rate != None %}
                                ["{{ year.year }}", {{ year.clearance_rate }}, "<div class='ucr-tooltip'><h3>{{ year.year }}: <small>" + plural[crimeType].toUpperCase() + "</small></h3><p class='ucr-details'><strong>INCIDENTS:</strong> <span>{{ year.incidents }}</span><br/><strong>CLEARANCES:</strong><span> {{ year.clearances }}</span><br/><strong>CLEARANCE RATE:</strong><span> {{ year.clearance_rate }}</span></p></div> ",{{ year.group_clearance_rate }}] {% if not forloop.last %}, {% endif %}
                                {% endif %}
                            {% endfor %}
                        ]);

              var options = {
                      title: 'CLEARANCE RATE: PERCENTAGE OF ' + plural[crimeType].toUpperCase()  + ' CLEARED',
                      legend: { position: 'bottom' },
                      hAxis: {
                          gridlines: {count: {{ crime_stats | length }} }
                      },
                      vAxis: {format: '##%'},
                      pointSize: 6,
                      tooltip: {isHtml: true}
              };
            var chart = new google.visualization.LineChart(document.getElementById('clearance_chart'));
            chart.draw(data, options);
	
	 }
          {% endif %}

          {% if rate_chart %}

              google.charts.setOnLoadCallback(rateChart);

        function rateChart(){
            var data = new google.visualization.DataTable();
                data.addColumn("string", "YEAR");
                data.addColumn("number", "{{ jurisdiction | safe }} " + crimeType.toUpperCase() + " RATE");
                data.addColumn({'type': 'string', 'role': 'tooltip', 'p': {'html': true}});
                data.addColumn("number", 'U.S. AVERAGE ' + crimeType.toUpperCase() + ' RATE');

                data.addRows([
                        {% for year in crime_stats %}
                            {% if year.crime_rate != None %}
                                ["{{ year.year }}", {{ year.crime_rate }},
                                    "<div class='ucr-tooltip'> <h3>{{ year.year }}: <small>" + plural[crimeType].toUpperCase() + " </small></h3><p class='ucr-details'><strong>INCIDENTS REPORTED:&nbsp</strong><span>{{ year.incidents }} </span><br/><strong>RATE: </strong><span>{{ year.crime_rate }}</span> per 100,000 residents</p></div>",
                                    {{ year.group_rate }}] {% if not forloop.last %}, {% endif %}
                            {% endif %}
                        {% endfor %}
                    ]);

            var options = {
                title: 'CRIME RATE: NUMBER OF ' + plural[crimeType].toUpperCase() + ' PER 100,000 RESIDENTS',
                legend: { position: 'bottom' },
                tooltip: {isHtml: true}
            };
            var chart = new google.visualization.ColumnChart(document.getElementById('rate_chart'));
            chart.draw(data, options);
        }
	
          {% endif %}
 </script>
</head>
<body>
<div class="container">
    <ol class="breadcrumb">
        <li>
            <a href="{% url 'ucr:base' %}">HOME</a>
        </li>
        <li>
            <a href="{% url 'ucr:department_select' county %}">{{ county }} COUNTY</a>
        </li>
            <li class="active">{{ jurisdiction }}</li>

    </ol>
    <div class="row">
        <div class="col-sm-12">
            <h2>{{ jurisdiction }}</h2>
        </div>
    </div>
    <div class="row">
      	<div class="col-sm-6 well">
		<p>Select which type of crime to display details for</p>	    
	<div class="col-sm-6">	
	   <form>
                <div class="form-group">
               	<select id="crime-type-select" class="form-control">
                        <option value="violent" {% if crime == 'violent' %}selected{% endif %}>Violent Crime</option>
                        <option value="property" {% if crime == 'property' %}selected{% endif %}>Property Crime</option>
                        <option value="homicide" {% if crime == 'homicide' %}selected{% endif %}>Homicide</option>
                        <option value="rape" {% if crime == 'rape' %}selected{% endif %}>Rape</option>
                        <option value="robbery" {% if crime == 'robbery' %}selected{% endif %}>Robbery</option>
                        <option value="aggravated_assault" {% if crime == 'aggravated_assault' %}selected{% endif %}>Aggravated Assault</option>
                        <option value="burglary" {% if crime == 'burglary' %}selected{% endif %}>Burglary</option>
                        <option value="larceny" {% if crime == 'larceny' %}selected{% endif %}>Larceny</option>
                        <option value="gta" {% if crime == 'vehicle theft' %}selected{% endif %}>Vehicle Theft</option>
                    </select>
                </div>
            </form>
        </div>
            <div class="col-sm-6">
                <button id="getCrimeStats" type="button" class="btn btn-primary btn-block">GO</button>
            </div>
	</div>    

	<div class="col-sm-6">
		<p>Crime rates are calculated as number of incidents per 100,000 people. This display allows for a look at rates over a ten-year period for the seven "index" crimes tracked by the FBI, plus composite measures tracking all violent crimes and all property crimes.</p>
		<p>A case is considerd 'cleared' when police make an arrest or have enough evidence to make one but are prevented from doing so because of something outside the department's control.</p>
	</div>
    </div>        

    <div class="row">

                <div class="col-md-12">
                    {% if clearance_chart == False %}
                        <p><b>No clearance rate data avaiable for {{ jurisdiction }}</b></p>
                    {% endif %}
                    {% if clearance_chart == True %}
                        <div id="rate_chart" style="width:100%;height:250px;"></div>
                    {% endif %}
                </div>

                <div class="col-md-12">


                    {% if rate_chart == False %}
                        <p><b>No crime rate data available for {{ jurisdiction }}</b></p>
                    {% endif %}
                    {% if rate_chart == True %}
                        <div id="clearance_chart" style="width:100%;height:250px;"></div>
                    {% endif %}
                </div>
    </div>


    <div class="row">
        <div class="center-block col-md-8 col-md-offset-2"><h4>Sources: All the data displayed was filed by the agencies themselves as part of the FBI's Uniform Crime Reporting program.</h4></div>
	<div class="well col-md-8 col-md-offset-2">
            <h3>The Fine Print</h3>
            <p>
                <small>
                    AVERAGE RATE: Average crime and clearances rates are for jurisdictions of similar population size as defined by the FBI.  There are a total of seven categories ranging from group 1, for jurisdictions with 250,000+ population to group 7, for jurisdictions with 10,000 or fewer people.
		</small>
            </p>
            <p>
                <small>
                    CLEARANCES: According to the FBI, A crime is cleared either when an arrest (not necessarily a conviction) is made or when the perpetrator has been identified and law enforcement has enough evidence to prosecute but some circumstance outside the agency's control prevents prosecution.  Examples of this include if the perpetrator is dead, witnesses refuse to cooperate with prosecution, or if the offender is jailed in some other jurisdiction and not extradited.
                </small>
            </p>
            <p>
                <small>
                    WHY IS THERE A CLEARANCE RATE ABOVE 100%? Clearances are recorded based on the year of the <em>clearance</em> not necessarily the year of the crime. So if a crime occurs in December and an arrest is made in January, the clearance is recorded for the second year.
		</small>
            </p>
            <p>
	

	</div>
    </div>
</div>
</body>

<script>
	var pymChild = new pym.Child({ id:'crimesandclearances' });      
    $(function(){
        $("#getCrimeStats").click(function(){
            let indexCrime, currentURL, newURL;
            currentURL = window.location.href;
            currentURL = currentURL.split('/');
            indexCrime = $('#crime-type-select').val();
            currentURL[currentURL.length - 2] = indexCrime;
            newURL = currentURL.join('/');
            window.location.href = newURL;
        })
    });

</script>



</html>

templates/ucr/templates/county_agencies.html
<h1>{{ county }}</h1>

<ul>
    {% for agency in county_agencies %}
        <li>{{ agency.department }} violent: {{ agency.r_violent_16 }}</li>
    {% endfor %}
</ul>

templates/ucr/templates/department_select.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Select Law Enforcement Agency</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.css" />
    <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
	<script type="text/javascript" src="https://pym.nprapps.org/pym.v1.min.js"></script>

</head>
<body>
<div class="container">
    <ol class="breadcrumb">
        <li>
            <a href="{% url "ucr:base" %}">HOME</a>
        </li>
        <li>
            <a href="{% url "ucr:department_select" county %}">{{ county }}</a>
        </li>
            <li class="active">AGENCY</li>

    </ol>
	<div class="page-header">
		<h1>Crimes & Clearances</h1>
	</div>
	
    <h2>{{ county }} COUNTY</h2>
    <div class="row">
        <div class="col-md-6">
            <form class="form-inline">
                <div class="form-group">
                    <label for="department-select">Select Agency</label>
                    <select id="department-select" class="form-control">
                        {% for department in departments %}
                            <option value="{{ department.1 }}">{{ department.0 }}</option>
                        {% endfor %}
                    </select>
                </div>
                <button id="getDepartmentDetail" type="button" class="btn btn-primary">GO</button>
            </form>
        </div>
    </div>
</div>
<script>
    var pymChild = new pym.Child({ id: 'crimesandclearances' });

    $(function(){
        $('#getDepartmentDetail').click(function(){
            const base_url = "http://projects.yakimaherald.com:8888/clearances/ucr/";
            let department_selected = $('#department-select').val();
            window.location.href = base_url + department_selected + '/violent/';
        })
    })


</script>


</body>
</html>

templates/ucr/templates/nodata.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>No data available for that year</h1>
</body>
</html>